name: Functions test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run test script
      run: |
         chmod +x ./bashutilities-test.sh
         ./bashutilities-test.sh
      shell: bash
