name: Functions test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Run test script
        run: . ./bashutilities-test.sh
        shell: bash
